### ISSUE TITLE
Problème de mon coté

### ISSUE THREAD

**Issue by Army-py** [MrSpaar/discord-bot#1]
Salut,

Je me suis un peu inspiré de quelques unes de tes commandes et j'ai un petit problème de mon côté.
J'ai une erreur qui revient souvent quand mon bot joue de la musique qui est `Error in the pull function.`,
cela est à cause des options d'FFmpeg mais certaines de ses options de sont pas valide, voici le message d'erreur : `Unrecognized option 'reconnect_streamed'. |  Error splitting the argument list: Option not found`.

Du coup je te contacte pour savoir si tu as une solution ? Je continu les recherches de mon côtés.

**Comment by MrSpaar** [comment]
Après avoir fait quelques recherches, je vois que ce type d'erreur peut être du à la version de FFmpeg que tu utilises ou à la manière dont tu as installé FFmpeg. Malheureusement, je ne m'y connais pas trop à ce sujet donc je ne peux pas trop t'aider, désolé :/

**Comment by Army-py** [comment]
Merci pour la réponse ^^ Je vais me renseigner un peu plus du coup.

Merci pour ton aide ^^
