### ISSUE TITLE
How can I fix this error? 'ClientException: ffmpeg was not found.'

### ISSUE THREAD

**Issue by Dipuzer** [MrSpaar/discord-bot#2]
`voice.play(discord.FFmpegPCMAudio(song['source'], **self.FFMPEG_OPTIONS), after=lambda e: play_next(ctx))`
i have error in this sentence

**Comment by Dipuzer** [comment]
I installed all modules

**Comment by MrSpaar** [comment]
Could you show me the error ?

**Comment by MrSpaar** [comment]
Have you added "ffmpeg" to path ?

**Comment by Dipuzer** [comment]
Oh! I forgot it. Thanks! :D

**Comment by Dipuzer** [comment]
But.. i have something wrong.
`[tls @ 000001e7e575b280] Error in the pull function.
[https @ 000001e7e575cc40] Will reconnect at 851968 in 0 second(s), error=I/O error.`
What is this?

**Comment by MrSpaar** [comment]
My bot doesn't download videos, so he need access to a websocket (path to the video audio file).

Youtube (and some others website, like Soundcloud) gives a restricted access to bots : 
After a certain period, Youtube closes this websocket. If the bot doesn't reconnect to the websocket, it won't be able to play the video anymore. When that happens, you have this message in the console, which tells you that the bot is reconnecting to the websocket.
