### ISSUE TITLE
Playing Music

### ISSUE THREAD

**Issue by watermelonnull** [MrSpaar/discord-bot#4]
At first I forgot to put FFMPEG into the correct path, after that issue was fix, this error message came up. 

command raised an exception: OpusNotLoaded: 

Any ideas on what it could be?

**Comment by MrSpaar** [comment]
Discord uses opus to compress audio data so you have to install it: [How to install Opus?](https://github.com/discordrb/discordrb/wiki/Installing-libopus).
If you're running your bot on heroku, you need to add this to your buildpacks: https://github.com/xrisk/heroku-opus.git

**Comment by watermelonnull** [comment]
ok ty:)
